name: Build backend
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'gfa-backend/**'
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Do this
        run: echo 'Build backend'
