name: Copy backend
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '!gfa-backend/**'
jobs:
  copy-backend:
  runs-on: ubuntu-latest
  steps:
    - name: Do this
      run: echo 'Copy backend'
