name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Obtain PR number
        run: |
          PR_NUMBER=$(curl -s -H "Accept: application/vnd.github.groot-preview+json" https://api.github.com/repos/Dunklas/gbg-farligt-avfall/commits/$GITHUB_SHA/pulls | jq -r '.[0].number')
          echo "::set-output name=number::$PR_NUMBER"
        id: pull_request
      
      - name: Deploy to AWS
        uses: youyo/aws-cdk-github-actions@v1
        with:
          working_dir: 'gfa-iac'
          cdk_subcommand: "deploy -c artifactsBucketName=${{ secrets.S3_ARTIFACT_BUCKET }} -c version=${{ steps.pull_request.outputs.number }}"
          actions_comment: false
      
      - name: Obtain API url
        run: |
          API_URL=$(aws cloudformation describe-stacks --stack-name GbgFarligtAvfallStack --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
          echo "::set-output name=url::$API_URL"
        id: api_endpoint

      - name: Obtain web hosting bucket
        run: |
          WEB_BUCKET=$(aws cloudformation describe-stacks --stack-name GbgFarligtAvfallStack --query "Stacks[0].Outputs[?OutputKey=='WebBucket'].OutputValue" --output text)
          echo "::set-output name=bucket::$WEB_BUCKET"
        id: web_hosting

      - name: Build/Deploy frontend
        run: |
          cd gfa-frontend 
          API_URL=${{ steps.api_endpoint.outputs.url }} npm run build
          aws s3 sync build s3://${{ steps.web_hosting.outputs.bucket }}
