name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      
      - name: Obtain PR number
        run: echo "##[set-output name=number;]$(curl -s -H 'Accept: application/vnd.github.groot-preview+json' https://api.github.com/repos/Dunklas/gbg-farligt-avfall/commits/$GITHUB_SHA/pulls | jq -r '.[0].number')"
        id: pull_request
      
      - name: Print PR number
        run: echo "PR Number - ${{ steps.pull_request.outputs.number }}"

      - name: Deploy to AWS
        uses: youyo/aws-cdk-github-actions@v1
        with:
          working_dir: 'gfa-iac'
          cdk_subcommand: "deploy -c artifactsBucketName=${{ secrets.S3_ARTIFACT_BUCKET }} -c version=${{ steps.pull_request.outputs.number }}"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
